// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Category struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Event struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Location    string         `json:"location"`
	AgeRange    string         `json:"age_range"`
	UserID      int32          `json:"user_id"`
}

type EventCategory struct {
	EventID    int32 `json:"event_id"`
	CategoryID int32 `json:"category_id"`
}

type User struct {
	ID       int32          `json:"id"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Age      sql.NullTime   `json:"age"`
	Industry sql.NullString `json:"industry"`
	Role     string         `json:"role"`
}

type UserPreference struct {
	UserID     int32 `json:"user_id"`
	CategoryID int32 `json:"category_id"`
}
