// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const addEventCategory = `-- name: AddEventCategory :exec
INSERT INTO event_category (event_id, category_id)
VALUES ($1, $2)
ON CONFLICT (event_id, category_id) DO NOTHING
`

type AddEventCategoryParams struct {
	EventID    int32 `json:"event_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) AddEventCategory(ctx context.Context, arg AddEventCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addEventCategory, arg.EventID, arg.CategoryID)
	return err
}

const addUserPreference = `-- name: AddUserPreference :exec
INSERT INTO user_preference (user_id, category_id)
VALUES ($1, $2)
ON CONFLICT (user_id, category_id) DO NOTHING
`

type AddUserPreferenceParams struct {
	UserID     int32 `json:"user_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) AddUserPreference(ctx context.Context, arg AddUserPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, addUserPreference, arg.UserID, arg.CategoryID)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO category (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO event (title, description, location, age_range, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, location, age_range, user_id
`

type CreateEventParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Location    string         `json:"location"`
	AgeRange    string         `json:"age_range"`
	UserID      int32          `json:"user_id"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.AgeRange,
		arg.UserID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.AgeRange,
		&i.UserID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (name, email, age, industry, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, age, industry, role
`

type CreateUserParams struct {
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Age      sql.NullTime   `json:"age"`
	Industry sql.NullString `json:"industry"`
	Role     string         `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Age,
		arg.Industry,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Age,
		&i.Industry,
		&i.Role,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM category
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM event
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const deleteEventCategories = `-- name: DeleteEventCategories :exec
DELETE FROM event_category
WHERE event_id = $1
`

func (q *Queries) DeleteEventCategories(ctx context.Context, eventID int32) error {
	_, err := q.db.ExecContext(ctx, deleteEventCategories, eventID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user"
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getCategoriesByEvent = `-- name: GetCategoriesByEvent :many
SELECT c.id, c.name
FROM category c
JOIN event_category ec ON c.id = ec.category_id
WHERE ec.event_id = $1
`

func (q *Queries) GetCategoriesByEvent(ctx context.Context, eventID int32) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, name
FROM category
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, title, description, location, age_range, user_id
FROM event
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int32) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.AgeRange,
		&i.UserID,
	)
	return i, err
}

const getPreferencesByUser = `-- name: GetPreferencesByUser :many
SELECT c.id, c.name
FROM category c
JOIN user_preference up ON c.id = up.category_id
WHERE up.user_id = $1
`

func (q *Queries) GetPreferencesByUser(ctx context.Context, userID int32) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getPreferencesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, age, industry, role
FROM "user"
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Age,
		&i.Industry,
		&i.Role,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name
FROM category
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventCategories = `-- name: ListEventCategories :many
SELECT c.id, c.name
FROM category c
JOIN event_category ec ON c.id = ec.category_id
WHERE ec.event_id = $1
ORDER BY c.name
`

func (q *Queries) ListEventCategories(ctx context.Context, eventID int32) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listEventCategories, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, description, location, age_range, user_id
FROM event
ORDER BY id DESC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.AgeRange,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPreferences = `-- name: ListUserPreferences :many
SELECT c.id, c.name
FROM category c
JOIN user_preference up ON c.id = up.category_id
WHERE up.user_id = $1
ORDER BY c.name
`

func (q *Queries) ListUserPreferences(ctx context.Context, userID int32) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listUserPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, age, industry, role
FROM "user"
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Age,
			&i.Industry,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEventCategory = `-- name: RemoveEventCategory :exec
DELETE FROM event_category
WHERE event_id = $1 AND category_id = $2
`

type RemoveEventCategoryParams struct {
	EventID    int32 `json:"event_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) RemoveEventCategory(ctx context.Context, arg RemoveEventCategoryParams) error {
	_, err := q.db.ExecContext(ctx, removeEventCategory, arg.EventID, arg.CategoryID)
	return err
}

const removeUserPreference = `-- name: RemoveUserPreference :exec
DELETE FROM user_preference
WHERE user_id = $1 AND category_id = $2
`

type RemoveUserPreferenceParams struct {
	UserID     int32 `json:"user_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) RemoveUserPreference(ctx context.Context, arg RemoveUserPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, removeUserPreference, arg.UserID, arg.CategoryID)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE category
SET name = $2
WHERE id = $1
`

type UpdateCategoryParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory, arg.ID, arg.Name)
	return err
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE event
SET title = $2,
    description = $3,
    location = $4,
    age_range = $5,
    user_id = $6
WHERE id = $1
`

type UpdateEventParams struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Location    string         `json:"location"`
	AgeRange    string         `json:"age_range"`
	UserID      int32          `json:"user_id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.ExecContext(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.AgeRange,
		arg.UserID,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE "user"
SET name = $2,
    email = $3,
    age = $4,
    industry = $5,
    role = $6
WHERE id = $1
`

type UpdateUserParams struct {
	ID       int32          `json:"id"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Age      sql.NullTime   `json:"age"`
	Industry sql.NullString `json:"industry"`
	Role     string         `json:"role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Age,
		arg.Industry,
		arg.Role,
	)
	return err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
WITH deleted AS (
    DELETE FROM user_preference
    WHERE user_id = $1
)
INSERT INTO user_preference (user_id, category_id)
SELECT $1, category_id
FROM unnest($2::int[]) AS category_id
ON CONFLICT (user_id, category_id) DO NOTHING
`

type UpdateUserPreferencesParams struct {
	UserID  int32   `json:"user_id"`
	Column2 []int32 `json:"column_2"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPreferences, arg.UserID, pq.Array(arg.Column2))
	return err
}
